language: java
install: true
sudo: required
services:
  - docker
jdk:
  - openjdk8

script:
  - ./gradlew clean integrationTest --tests com.solace.messaging.kafka.it.SourceConnectorIT

after_success:
- >
  if [ "$TRAVIS_BRANCH" = "SourceConnectorProductization" ]; then
    git config --global user.email "travis@travis-ci.org";
    git config --global user.name "travis-ci";
    mkdir gh-pages; # Now update gh-pages
    git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/SolaceDev/pubsubplus-connector-kafka-source gh-pages > /dev/null 2>&1;
    mv build/distributions gh-pages
    pushd gh-pages;
    git add -f .;
    git commit -m "Latest connector distribution on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages";
    git remote add origin-pages https://${GH_TOKEN}@github.com/SolaceDev/pubsubplus-connector-kafka-source.git > /dev/null 2>&1;
    git push --quiet --set-upstream origin-pages gh-pages;
    echo "Updated and pushed GH pages!";
    popd;
  fi
