language: java
install: true
sudo: required
services:
  - docker
jdk:
  - openjdk8

script:
  - ./gradlew clean integrationTest --tests com.solace.connector.kafka.connect.source.it.SourceConnectorIT

after_success:
- >
  if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    git config --global user.email "travis@travis-ci.org";
    git config --global user.name "travis-ci";
    mkdir gh-pages; # Now update gh-pages
    git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/SolaceProducts/pubsubplus-connector-kafka-source gh-pages > /dev/null 2>&1;
    rm gh-pages/downloads/pubsubplus-connector-kafka-source*
    mv build/distributions/pubsubplus-connector-kafka-source* gh-pages/downloads
    cd gh-pages;
    pushd downloads
    cp index.template index.html; FILENAME=`find . | grep *.zip | cut -d'/' -f2 | sed 's/.\{4\}$//'`;  sed -i "s/CONNECTOR_NAME/$FILENAME/g" index.html;
    popd;
    git add -f .;
    git commit -m "Latest connector distribution on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages";
    git remote add origin-pages https://${GH_TOKEN}@github.com/SolaceProducts/pubsubplus-connector-kafka-source.git > /dev/null 2>&1;
    git push --quiet --set-upstream origin-pages gh-pages;
    echo "Updated and pushed GH pages!";
  fi
